package com.orinocolabs.cowork_studio.identity.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Identity of a {@link User}, generated by the domain itself rather than by
 * the database. Generating the id in the domain (instead of relying on a JPA
 * {@code @GeneratedValue}) keeps aggregate creation fully testable without a
 * persistence context and lets the same id be referenced safely before the
 * first save.
 */
public final class UserId {

    private final UUID value;

    private UserId(UUID value) {
        this.value = Objects.requireNonNull(value, "id must not be null");
    }

    public static UserId newId() {
        return new UserId(UUID.randomUUID());
    }

    public static UserId of(UUID value) {
        return new UserId(value);
    }

    public static UserId of(String value) {
        return new UserId(UUID.fromString(value));
    }

    public UUID value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserId other)) return false;
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
